In [24]:
import numpy as np
 
arr=np.arange(0,10,2)


In [25]:
arr


array([0, 2, 4, 6, 8])

In [26]:
arr+1

array([1, 3, 5, 7, 9])

In [29]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr+arr1

ValueError: operands could not be broadcast together with shapes (5,) (10,) 

In [11]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
arr/arr

C:\Users\agrover\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.])

In [33]:
0/arr

C:\Users\agrover\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   0.,   0.,   0.,   0.])

In [14]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
np.max(arr)

9

In [1]:
mylist=[1,2,3,4]
mylist


[1, 2, 3, 4]

In [2]:
import numpy as np


In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [11]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [34]:
f=5


array([], dtype=int32)

In [7]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [40]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
np.ones((5,5))*5

array([[ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.,  5.]])

In [ ]:
*5

In [10]:
np.linspace(0,110,10)

array([   0.        ,   12.22222222,   24.44444444,   36.66666667,
         48.88888889,   61.11111111,   73.33333333,   85.55555556,
         97.77777778,  110.        ])

In [20]:
np.random.rand(5,5)

array([[ 0.26872064,  0.65001163,  0.6362304 ,  0.52112479,  0.18570841],
       [ 0.51358881,  0.37109746,  0.94644607,  0.04675801,  0.41645073],
       [ 0.51110793,  0.98076157,  0.23427252,  0.23080589,  0.10733546],
       [ 0.25226339,  0.36463844,  0.87720463,  0.33002121,  0.06231051],
       [ 0.36738408,  0.16447398,  0.18969217,  0.9981505 ,  0.89965274]])

In [33]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
randarr=np.random.randint(0,100,10)
randarr

array([85, 27, 78, 83, 49,  7, 27, 43, 20, 82])

In [15]:
arr1=randarr.reshape(5,4)
arr1


array([[18,  5,  9,  3],
       [20,  0,  0,  5],
       [24, 18, 23, 12],
       [23, 14,  3,  4],
       [13, 22, 12, 21]])

(2, 5)

In [45]:
np.ones((2,2))*5

array([[5., 5.],
       [5., 5.]])

In [46]:
import pandas as pd

In [48]:
label=['a','b','c','d']
list=[1,2,3,4]
dict={'a':10,'b':20,'c':30,'d':40}

In [57]:
p=pd.Series(data=list,index=label)

In [58]:
p

a    1
b    2
c    3
d    4
dtype: int64

In [56]:
p

0    1
1    2
2    3
3    4
dtype: int64

In [61]:
np.random.seed(101)

In [65]:
df=pd.DataFrame(arr1,[1,2,3,4,5],['a','b','c','d'])

In [66]:
df

a   b   c   d
1  11  17   6  23
2  11  15   9  13
3   8   4   8  21
4   0  14   5  12
5   8  17  19  15

In [ ]:
df.